name: docstring_generator_annotator
description: A simple dart annotator that can be used for generating docstrings for dart code. Inteded for use as a dependency of the 'docstring_generator' vscode extension.
version: 1.0.1
repository: https://github.com/xanmankey/docstring_generator_annotator_dart.git

environment:
  sdk: '>=2.18.6 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
